-- Fifty Store Supabase schema
-- Run this in a NEW Supabase project dedicated to Fifty Store.

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamp with time zone default now()
);

insert into public.app_settings (key, value)
values ('store_slug', 'fifty-store')
on conflict (key) do update set value = excluded.value, updated_at = now();

create table if not exists public.categories (
  id text primary key,
  slug text,
  name text not null
);

insert into public.categories (id, slug, name)
values
  ('all', 'all', 'Tous les produits'),
  ('iphones', 'iphones', 'iPhones'),
  ('cases', 'cases', 'Anticases & cages iPhone'),
  ('chargers', 'chargers', 'Chargeurs & cables'),
  ('headphones', 'headphones', 'Casques & ecouteurs'),
  ('smartwatches', 'smartwatches', 'Smartwatch'),
  ('powerbanks', 'powerbanks', 'Powerbanks'),
  ('speakers', 'speakers', 'Baffles'),
  ('accessories', 'accessories', 'Accessoires')
on conflict (id) do update set name = excluded.name, slug = excluded.slug;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null references public.categories(id),
  price numeric not null default 0,
  old_price numeric,
  discount numeric,
  rating numeric not null default 4.5,
  reviews int not null default 0,
  stock int not null default 0,
  image text,
  image_url text,
  images jsonb default '[]'::jsonb,
  video_url text,
  description text not null default '',
  specs jsonb default '[]'::jsonb,
  is_new boolean not null default true,
  is_best_seller boolean not null default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.social_media (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('instagram', 'tiktok')),
  image_url text not null,
  post_url text not null,
  caption text not null default '',
  created_at timestamp with time zone default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  city text,
  address text,
  created_at timestamp with time zone default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id),
  customer_name text not null,
  phone text not null,
  city text,
  address text,
  notes text,
  total numeric not null default 0,
  status text not null default 'En cours',
  payment_method text,
  delivery_method text,
  created_at timestamp with time zone default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint,
  product_name text not null,
  quantity int not null default 1,
  unit_price numeric not null default 0,
  total_price numeric not null default 0
);

create table if not exists public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  product_id bigint not null,
  created_at timestamp with time zone default now(),
  unique (user_id, product_id)
);

alter table public.app_settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.social_media enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.wishlist enable row level security;

create policy "public can verify app" on public.app_settings for select using (key = 'store_slug');
create policy "public can read categories" on public.categories for select using (true);
create policy "public can read products" on public.products for select using (true);
create policy "public can read social media" on public.social_media for select using (true);

create policy "admin can manage categories" on public.categories
for all using ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn')
with check ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn');

create policy "admin can manage products" on public.products
for all using ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn')
with check ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn');

create policy "admin can manage social media" on public.social_media
for all using ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn')
with check ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn');

create policy "public can create customers" on public.customers for insert with check (true);
create policy "public can update customers" on public.customers for update using (true) with check (true);
create policy "public can find customers" on public.customers for select using (true);

create policy "public can create orders" on public.orders for insert with check (true);
create policy "public can create order items" on public.order_items for insert with check (true);

create policy "admin can read orders" on public.orders
for select using ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn');

create policy "admin can update orders" on public.orders
for update using ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn')
with check ((auth.jwt() ->> 'email') = 'admin@fiftystore.tn');

create policy "users manage own wishlist" on public.wishlist
for all using (auth.uid() = user_id)
with check (auth.uid() = user_id);
